services:
  db:
    container_name: ${APP_NAME}_database
    image: mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    volumes:
      - C:\Users\izanv\OneDrive\Escritorio\2 ASIR\IAW\GitHub\bbdd\WebPDB:/var/lib/mysql
      - C:\Users\izanv\OneDrive\Escritorio\2 ASIR\IAW\GitHub\Docker\Entrega\WebPersonal\BBDD.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: $SQL_ROOT_PWD
      MYSQL_USER: $SQL_USER
      MYSQL_PASSWORD: $SQL_PASSWD
      MYSQL_DATABASE: $SQL_DBNAME
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    networks:
      net: 
        ipv4_address: 172.30.1.2

  www:
    build:
      context: .
    container_name: ${APP_NAME}_www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - ${HTTP_PORT}:80

    networks:
      net:
        ipv4_address: 172.30.1.3

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
