# Usa una imagen base de PHP con Apache
FROM php:${PHP_VERSION}-apache

# Instala las extensiones necesarias para Moodle
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd mysqli xmlrpc intl zip soap opcache \
    && a2enmod rewrite \
    && rm -rf /var/lib/apt/lists/*

# Copia los archivos de Moodle al contenedor
COPY ./moodle /var/www/html

# Configura los permisos para Moodle
RUN mkdir -p /var/www/moodledata && \
    chown -R www-data:www-data /var/www/html /var/www/moodledata && \
    chmod -R 755 /var/www/html /var/www/moodledata

# Exponemos los puertos (80 para HTTP, 443 para HTTPS)
EXPOSE 80 443

# Comando por defecto
CMD ["apache2-foreground"]
