# Eliminar la línea de versión
services:
  db:
    container_name: ${APP_NAME}-database
    image: ${DB_PROVIDER}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ../../../bbdd/MoodleDB:/var/lib/mysql
      - ../../../bbdd/MoodleRO:/docker-entrypoint-initdb.d/:ro
    networks:
      net: 
        ipv4_address: 172.21.1.2

  www:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${APP_NAME}-www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    links:
      - db:${DB_PROVIDER}
    volumes:
      - ${APP_DIR}:/var/www/html:cached
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    networks:
      net:
        ipv4_address: 172.21.1.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      net:
        ipv4_address: 172.21.1.4

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=${DB_NAME}
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=${DB_ROOT_PASSWORD}
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin
      - MOODLE_EMAIL=admin@example.com
    ports:
      - "8080:8080"
    volumes:
      - moodle_data:/bitnami
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 172.21.1.5

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24

volumes:
  moodle_data:
